name: Chess

on:
  issues:
    types: [opened]

permissions:
  issues: write # Allow commenting, labeling, and closing issues
  contents: write # Allow committing and pushing code changes

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Chess:')

    steps:
      # Set up environment variables
      - name: Setting up environment
        run: |
          echo ISSUE_NUMBER="${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo REPOSITORY_OWNER="${{ github.repository_owner }}" >> $GITHUB_ENV
          echo GITHUB_REPOSITORY="${{ github.repository }}" >> $GITHUB_ENV

      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Python
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      # Install dependencies and run main script
      - name: Play chess
        run: |
          pip install -r requirements.txt
          python main.py

      # Commit and push updated game files
      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${ISSUE_TITLE} by ${{ github.event.issue.user.login }}" || echo "No changes to commit"
          git push
